TRIP_CATEGORIES = [
    ('adventure', 'Adventure'),
    ('education', 'Education'),
    ('cultural', 'Cultural'),
    ('nature', 'Nature'),
    ('wellness', 'Wellness'),
    ('historical', 'Historical'),
    ('culinary', 'Culinary'),
    ('volunteer', 'Volunteer'),
    ('wildlife', 'Wildlife'),
    ('beach', 'Beach'),
    ('spiritual', 'Spiritual'),
    ('sports', 'Sports'),
    ('artistic', 'Artistic'),
    ('backpacking', 'Backpacking'),
    ('road_trip', 'Road Trip'),
    ('safari', 'Safari'),
    ('eco_tourism', 'Eco-tourism'),
    ('music_festival', 'Music Festival'),
    ('archaeological', 'Archaeological'),
    ('wine_tasting', 'Wine Tasting'),
    ('photography', 'Photography'),
    ('mountain_climbing', 'Mountain Climbing'),
    ('yoga_retreat', 'Yoga Retreat'),
    ('food_tour', 'Food Tour'),
    ('architecture', 'Architecture'),
    ('scuba_diving', 'Scuba Diving'),
    ('farm_stay', 'Farm Stay'),
    ('skiing_snowboarding', 'Skiing/Snowboarding'),
    ('river_rafting', 'River Rafting'),
    ('language_immersion', 'Language Immersion'),
    ('camping', 'Camping'),
    ('fishing', 'Fishing'),
    ('hiking', 'Hiking'),
    ('cultural_exchange', 'Cultural Exchange'),
    ('volcano_exploration', 'Volcano Exploration'),
    ('bird_watching', 'Bird Watching'),
    ('desert_safari', 'Desert Safari'),
    ('spa_retreat', 'Spa Retreat'),
    ('tea_plantation_visit', 'Tea Plantation Visit'),
    ('cultural_festival', 'Cultural Festival'),
    ('kayaking', 'Kayaking'),
    ('rainforest_expedition', 'Rainforest Expedition'),
    ('cycling_tour', 'Cycling Tour'),
    ('cruise', 'Cruise'),
    ('hot_air_ballooning', 'Hot Air Ballooning'),
    ('surfing', 'Surfing'),
    ('motorcycle_tour', 'Motorcycle Tour'),
    ('paragliding', 'Paragliding'),
    ('polar_expedition', 'Polar Expedition'),
]

LIKE_CHOICES = [
    ('like', 'like'),
    ('dislike', 'dislike'),
]