# Generated by Django 5.0.3 on 2024-03-10 08:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_userdetail_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uiid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_followings', to=settings.AUTH_USER_MODEL, to_field='email')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_followers', to=settings.AUTH_USER_MODEL, to_field='email')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
