# Generated by Django 5.0.3 on 2024-03-17 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_remove_userstatus_status_userstatus_is_online'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstatus',
            old_name='lost_lagin',
            new_name='logout_at',
        ),
    ]
