fake_trips = [
    {
        "user": "madhu@gmail.com",
        "title": "Adventure Trek in Himalayas",
        "address_from": "Manali, Himachal Pradesh",
        "address_to": "Auli, Uttarakhand",
        "category": "adventure",
        "date": "2024-07-15",
        "time": "08:00",
        "group_size": 5,
        "distance": 150,
        "description": "Join us for an exciting trekking adventure in the beautiful Himalayas.",
        "trip_cover_img": "https://via.placeholder.com/800x600?text=Adventure+Trek"
    },
    {
        "user": "madhu@gmail.com",
        "title": "Yoga Retreat in Goa",
        "address_from": "Arambol, Goa",
        "address_to": "Morjim, Goa",
        "category": "wellness",
        "date": "2023-03-01",
        "time": "10:00",
        "group_size": 10,
        "distance": 20,
        "description": "Relax and rejuvenate with our yoga retreat in the serene beaches of Goa.",
        "trip_cover_img": "https://via.placeholder.com/800x600?text=Yoga+Retreat"
    },
    {
        "user": "madhu@gmail.com",
        "title": "Cultural Tour of Rajasthan",
        "address_from": "Jaipur, Rajasthan",
        "address_to": "Udaipur, Rajasthan",
        "category": "cultural",
        "date": "2024-11-20",
        "time": "09:30",
        "group_size": 8,
        "distance": 400,
        "description": "Experience the rich cultural heritage of Rajasthan with our guided tour.",
        "trip_cover_img": "https://via.placeholder.com/800x600?text=Cultural+Tour"
    },
    {
        "user": "madhu@gmail.com",
        "title": "Wildlife Safari in Jim Corbett National Park",
        "address_from": "Delhi, India",
        "address_to": "Nainital, Uttarakhand",
        "category": "wildlife",
        "date": "2024-09-10",
        "time": "06:00",
        "group_size": 6,
        "distance": 300,
        "description": "Embark on an adventurous wildlife safari in the famous Jim Corbett National Park.",
        "trip_cover_img": "https://via.placeholder.com/800x600?text=Wildlife+Safari"
    },
    {
        "user": "madhu@gmail.com",
        "title": "Historical Tour of Agra",
        "address_from": "Delhi, India",
        "address_to": "Agra, Uttar Pradesh",
        "category": "historical",
        "date": "2023-02-05",
        "time": "11:00",
        "group_size": 12,
        "distance": 200,
        "description": "Explore the iconic historical monuments of Agra including the Taj Mahal.",
        "trip_cover_img": "https://via.placeholder.com/800x600?text=Historical+Tour"
    },
    {
        "user": "madhu@gmail.com",
        "title": "Culinary Tour in Mumbai",
        "address_from": "Mumbai, Maharashtra",
        "address_to": "Mumbai, Maharashtra",
        "category": "culinary",
        "date": "2023-04-20",
        "time": "07:30",
        "group_size": 8,
        "distance": 0,
        "description": "Indulge in the diverse flavors of Mumbai with our culinary tour across the city.",
        "trip_cover_img": "https://via.placeholder.com/800x600?text=Culinary+Tour"
    },
    {
        "user": "madhu@gmail.com",
        "title": "Beach Vacation in Andaman Islands",
        "address_from": "Port Blair, Andaman and Nicobar Islands",
        "address_to": "Havelock Island, Andaman and Nicobar Islands",
        "category": "beach",
        "date": "2023-06-15",
        "time": "09:00",
        "group_size": 4,
        "distance": 60,
        "description": "Escape to the pristine beaches of the Andaman Islands for a relaxing vacation.",
        "trip_cover_img": "https://via.placeholder.com/800x600?text=Beach+Vacation"
    },
    {
        "user": "madhu@gmail.com",
        "title": "Nature Retreat in Kerala",
        "address_from": "Kochi, Kerala",
        "address_to": "Munnar, Kerala",
        "category": "nature",
        "date": "2023-09-30",
        "time": "08:30",
        "group_size": 6,
        "distance": 130,
        "description": "Immerse yourself in the serene beauty of Kerala with our nature retreat in Munnar.",
        "trip_cover_img": "https://via.placeholder.com/800x600?text=Nature+Retreat"
    },
    {
        "user": "madhu@gmail.com",
        "title": "Skiing Adventure in Gulmarg",
        "address_from": "Srinagar, Jammu and Kashmir",
        "address_to": "Gulmarg, Jammu and Kashmir",
        "category": "adventure",
        "date": "2024-12-25",
        "time": "10:00",
        "group_size": 8,
        "distance": 50,
        "description": "Experience the thrill of skiing amidst the snow-capped mountains of Gulmarg.",
        "trip_cover_img": "https://via.placeholder.com/800x600?text=Skiing+Adventure"
    },
    {
        "user": "madhu@gmail.com",
        "title": "Photography Tour in Varanasi",
        "address_from": "Varanasi, Uttar Pradesh",
        "address_to": "Varanasi, Uttar Pradesh",
        "category": "photography",
        "date": "2023-01-10",
        "time": "05:30",
        "group_size": 10,
        "distance": 0,
        "description": "Capture the essence of Varanasi with our photography tour along the ghats and streets of the city.",
        "trip_cover_img": "https://via.placeholder.com/800x600?text=Photography+Tour"
    },
    {
        "user": "madhu@gmail.com",
        "title": "Road Trip to Ladakh",
        "address_from": "Leh, Ladakh",
        "address_to": "Leh, Ladakh",
        "category": "road_trip",
        "date": "2023-07-20",
        "time": "06:00",
        "group_size": 4,
        "distance": 600,
        "description": "Embark on an epic road trip adventure to the enchanting landscapes of Ladakh.",
        "trip_cover_img": "https://via.placeholder.com/800x600?text=Road+Trip"
    },
    {
        "user": "madhu@gmail.com",
        "title": "Music Festival in Pune",
        "address_from": "Pune, Maharashtra",
        "address_to": "Pune, Maharashtra",
        "category": "music_festival",
        "date": "2023-12-01",
        "time": "03:00",
        "group_size": 15,
        "distance": 0,
        "description": "Groove to the beats of live music at the vibrant music festival in Pune.",
        "trip_cover_img": "https://via.placeholder.com/800x600?text=Music+Festival"
    },
    {
        "user": "madhu@gmail.com",
        "title": "Volunteer Trip to Uttarakhand",
        "address_from": "Dehradun, Uttarakhand",
        "address_to": "Rishikesh, Uttarakhand",
        "category": "volunteer",
        "date": "2023-08-10",
        "time": "09:00",
        "group_size": 10,
        "distance": 50,
        "description": "Make a difference by volunteering for community projects in the scenic Uttarakhand region.",
        "trip_cover_img": "https://via.placeholder.com/800x600?text=Volunteer+Trip"
    },
    {
        "user": "madhu@gmail.com",
        "title": "Artistic Retreat in Pondicherry",
        "address_from": "Pondicherry, Tamil Nadu",
        "address_to": "Pondicherry, Tamil Nadu",
        "category": "artistic",
        "date": "2023-05-05",
        "time": "11:00",
        "group_size": 6,
        "distance": 0,
        "description": "Unleash your creativity with our artistic retreat in the charming town of Pondicherry.",
        "trip_cover_img": "https://via.placeholder.com/800x600?text=Artistic+Retreat"
    },
    {
        "user": "madhu@gmail.com",
        "title": "Eco-tourism Expedition in Western Ghats",
        "address_from": "Coimbatore, Tamil Nadu",
        "address_to": "Munnar, Kerala",
        "category": "eco_tourism",
        "date": "2024-01-15",
        "time": "08:00",
        "group_size": 8,
        "distance": 250,
        "description": "Explore the biodiversity of the Western Ghats with our eco-tourism expedition.",
        "trip_cover_img": "https://via.placeholder.com/800x600?text=Eco-tourism+Expedition"
    },
    {
        "user": "madhu@gmail.com",
        "title": "Language Immersion Program in Jaipur",
        "address_from": "Jaipur, Rajasthan",
        "address_to": "Jaipur, Rajasthan",
        "category": "language_immersion",
        "date": "2023-10-20",
        "time": "10:30",
        "group_size": 12,
        "distance": 0,
        "description": "Immerse yourself in the rich culture and language of Jaipur with our language immersion program.",
        "trip_cover_img": "https://via.placeholder.com/800x600?text=Language+Immersion"
    },
    {
        "user": "madhu@gmail.com",
        "title": "River Rafting Adventure in Rishikesh",
        "address_from": "Haridwar, Uttarakhand",
        "address_to": "Rishikesh, Uttarakhand",
        "category": "river_rafting",
        "date": "2024-09-01",
        "time": "07:00",
        "group_size": 6,
        "distance": 20,
        "description": "Experience the adrenaline rush of river rafting in the rapids of Rishikesh.",
        "trip_cover_img": "https://via.placeholder.com/800x600?text=River+Rafting+Adventure"
    },
    {
        "user": "madhu@gmail.com",
        "title": "Desert Safari in Jaisalmer",
        "address_from": "Jaisalmer, Rajasthan",
        "address_to": "Jaisalmer, Rajasthan",
        "category": "desert_safari",
        "date": "2023-11-10",
        "time": "04:00",
        "group_size": 8,
        "distance": 0,
        "description": "Embark on an unforgettable desert safari adventure amidst the golden sands of Jaisalmer.",
        "trip_cover_img": "https://via.placeholder.com/800x600?text=Desert+Safari"
    },
    {
        "user": "madhu@gmail.com",
        "title": "Fishing Trip in Kerala Backwaters",
        "address_from": "Kochi, Kerala",
        "address_to": "Alleppey, Kerala",
        "category": "fishing",
        "date": "2024-11-05",
        "time": "06:30",
        "group_size": 4,
        "distance": 50,
        "description": "Enjoy a tranquil fishing experience amidst the scenic backwaters of Kerala.",
        "trip_cover_img": "https://via.placeholder.com/800x600?text=Fishing+Trip"
    }
]
