# Generated by Django 5.0.3 on 2024-03-05 13:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uiid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('address_from', models.JSONField(default=dict)),
                ('address_to', models.JSONField(default=dict)),
                ('category', models.CharField(choices=[('adventure', 'Adventure'), ('education', 'Education'), ('cultural', 'Cultural'), ('nature', 'Nature'), ('wellness', 'Wellness'), ('historical', 'Historical'), ('culinary', 'Culinary'), ('volunteer', 'Volunteer'), ('wildlife', 'Wildlife'), ('beach', 'Beach'), ('spiritual', 'Spiritual'), ('sports', 'Sports'), ('artistic', 'Artistic'), ('backpacking', 'Backpacking'), ('road_trip', 'Road Trip'), ('safari', 'Safari'), ('eco_tourism', 'Eco-tourism'), ('music_festival', 'Music Festival'), ('archaeological', 'Archaeological'), ('wine_tasting', 'Wine Tasting'), ('photography', 'Photography'), ('mountain_climbing', 'Mountain Climbing'), ('yoga_retreat', 'Yoga Retreat'), ('food_tour', 'Food Tour'), ('architecture', 'Architecture'), ('scuba_diving', 'Scuba Diving'), ('farm_stay', 'Farm Stay'), ('skiing_snowboarding', 'Skiing/Snowboarding'), ('river_rafting', 'River Rafting'), ('language_immersion', 'Language Immersion'), ('camping', 'Camping'), ('fishing', 'Fishing'), ('hiking', 'Hiking'), ('cultural_exchange', 'Cultural Exchange'), ('volcano_exploration', 'Volcano Exploration'), ('bird_watching', 'Bird Watching'), ('desert_safari', 'Desert Safari'), ('spa_retreat', 'Spa Retreat'), ('tea_plantation_visit', 'Tea Plantation Visit'), ('cultural_festival', 'Cultural Festival'), ('kayaking', 'Kayaking'), ('rainforest_expedition', 'Rainforest Expedition'), ('cycling_tour', 'Cycling Tour'), ('cruise', 'Cruise'), ('hot_air_ballooning', 'Hot Air Ballooning'), ('surfing', 'Surfing'), ('motorcycle_tour', 'Motorcycle Tour'), ('paragliding', 'Paragliding'), ('polar_expedition', 'Polar Expedition')], max_length=30)),
                ('date', models.DateTimeField()),
                ('group_size', models.SmallIntegerField(default=3)),
                ('distance', models.IntegerField(null=True)),
                ('description', models.TextField(blank=True)),
                ('user_name', models.CharField(blank=True, max_length=30)),
                ('connected_users', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('comments', models.PositiveIntegerField(default=0)),
                ('requests', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
