# Generated by Django 5.0.3 on 2024-03-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='user_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
