# Generated by Django 5.0.3 on 2024-03-05 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trips', '0003_alter_trip_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='time',
            field=models.TimeField(default=datetime.time(22, 46, 20, 454731)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip',
            name='date',
            field=models.DateField(),
        ),
    ]
