# Generated by Django 5.0.3 on 2024-03-06 07:54

import helper.validations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trips', '0005_alter_trip_address_from_alter_trip_address_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='trip_cover_img',
            field=models.ImageField(blank=True, null=True, upload_to='trip_cover_images', validators=[helper.validations.validate_trip_image_size]),
        ),
        migrations.AlterField(
            model_name='trip',
            name='group_size',
            field=models.SmallIntegerField(default=2),
        ),
    ]
