# Generated by Django 5.0.3 on 2024-03-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trips', '0008_alter_tripcomment_user_alter_triplike_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='triplike',
            name='dis_like',
            field=models.BooleanField(default=False),
        ),
    ]
