# Generated by Django 5.0.3 on 2024-03-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trips', '0012_trip_is_published_remove_trip_connected_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='category',
            field=models.CharField(max_length=30),
        ),
    ]
